### ISSUE TITLE
Performance Issue - Kick Embed

### ISSUE THREAD

**Issue by GameplayStudent** [destinygg/chat-gui#260]
Over the past month or so, I've noticed that leaving the site open for a indetermined length of time (>3-5 hours) even in the background can cause performance issues cross pc with a laggy mouse, and generally unresponsive situation pc wide. However, the second I close the site all said performance issues cease. If I wait a few minutes and reboot the site (or close down my browser and boot it up again) the issue usually stops, but I've had it happen at least 12 times over the past month across two different pcs. My theory is a memory leak, but it's a hunch off of similar issues in my projects.

**Comment by Riott** [comment]
Probably not overly related to the above issue but a quick firefox profile of dgg chat and my local dgg chat dev instance i'm seeing a ton of repaints being done (probably not easily avoidable due to the nature of the application) but specifically the emote animations using `background-position-x` and  `background-position-y` I believe these could be causing repaints of siblings so potentially there could be optimisations that can be made in the emotes css maybe a `will-change` property or similar.

![image](https://github.com/destinygg/chat-gui/assets/1808209/28a5d59a-a75b-4877-b93e-3bed60e98017)

![image](https://github.com/destinygg/chat-gui/assets/1808209/167f9af3-6c83-4317-9846-6da9dc52dfc8)

![image](https://github.com/destinygg/chat-gui/assets/1808209/0f280c0f-3653-40bd-ac49-060bbabe381f)

**Comment by GameplayStudent** [comment]
I noticed today that the site was fine for 1.5 hours, but immediately began lagging when he started streaming on Kick

**Comment by GameplayStudent** [comment]
Now that tiny is streaming on Youtube/Rumble again, I can say it only occurs when he's streaming on Kick. I'm not sure what changes between the embeds, but I have yet to see it happen during any other embed.

**Comment by GameplayStudent** [comment]
Since tiny has talked about stopping embeds, this issue is no longer relevant.
