### ISSUE TITLE
README.md local development instructions are not sufficient to begin development

### ISSUE THREAD

**Issue by bmckalip** [destinygg/chat-gui#59]
I am interested in contributing to this project, and so I cloned the repo and followed the steps in the readme to get started.

I tried running install and start and receiving this error:

```
ERROR in ./fonts/AmongUs-Regular.ttf 1:0
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
 @ ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js!./assets/chat/css/style.scss 14:0-79 27:73-102
 @ ./assets/chat/css/style.scss 2:12-189 9:17-24 13:15-29
 @ ./assets/demo.js 2:0-30
```

I tried this on node versions 19.x.x, 12.9.0, and 6.x.x to no avail. The package.json states that node version 5 is required, but that is likely  not accurate. 

I also tried running the "glue" and "tld" scripts to see if this was relevant.

onboarding steps should be more clear in the readme to prevent this from happening. . I will continue debugging this and update here if I am unable to unblock myself, and submit a PR to improve the readme if so.

**Comment by bmckalip** [comment]
after some googling, it seems I can add this to the webpack module rules section to allow tiff files to be processed properly in webpack 5:

```
            {
                test: /\.(woff|woff2|eot|ttf|otf)$/i,
                type: 'asset/resource',
            },
```
 after doing this, the server starts. However, I am still experiencing issues at runtime, which I will continue to debug and report on here (this is now my personal manifesto page)

**Comment by 11k** [comment]
I worked on the sus font issue myself and used file-loader. It turns out file-loader is deprecated, so you did a better job by using asset modules.

The other issue you're probably running into has to do with importing HTML files in `assets/demo.js`. html-loader generates ES modules by default, but the file uses CJS `require` statements. To fix the issue, you need to `import` the HTML files, disable [this](https://webpack.js.org/loaders/html-loader/#esmodule) option for the loader in your Webpack config, or rely on Node's module interoperability features by appending `.default` to the `require`s.

I already improved the README and solved these issues in https://github.com/destinygg/chat-gui/pull/60, but I have some bad news: you can't connect to Destiny.gg chat like this because of how the server is configured. I'm not sure if we'll ever reconfigure the server to allow this to happen.

You can get around this with limited functionality by setting up a WebSocket proxy server. You have to connect the proxy server to the chat, then the dev server to the proxy server.
